// Generated by CoffeeScript 1.9.2
(function() {
  describe('first suite', function() {
    it('should be ok', function() {
      return expect(true).toBe(true);
    });
    it('should be ok', function() {
      return expect(true).toBe(true);
    });
    it('should failed', function() {
      return expect(true).toBe(false);
    });
    return it('should be ok', function() {
      return expect(true).toBe(true);
    });
  });

  describe('second suite', function() {
    it('should failed', function() {
      return expect(true).toBe(false);
    });
    it('should be ok', function() {
      return expect(true).toBe(true);
    });
    return describe('first child suite', function() {
      describe('first grandchild suite', function() {
        it('should failed', function() {
          expect(true).toBe(false);
          expect(true).toBe(false);
          return expect(true).toBe(true);
        });
        it('should failed', function() {
          return expect(true).toBe(false);
        });
        return it('should be ok', function() {
          return expect(true).toBe(true);
        });
      });
      return describe('second grandchild suite', function() {
        it('should failed', function() {
          return expect(true).toBe(false);
        });
        return it('should be ok', function() {
          return expect(true).toBe(true);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=example-spec.js.map
