// Generated by CoffeeScript 1.9.2
(function() {
  var SpecReporter;

  SpecReporter = require('../src/jasmine-spec-reporter.js');

  describe('duration', function() {
    return it('should be human readable', function() {
      var hours, mins, reporter, secs;
      secs = 1000;
      mins = 60 * secs;
      hours = 60 * mins;
      reporter = new SpecReporter();
      this.formatDuration = reporter.metrics.formatDuration;
      expect(this.formatDuration(0)).toBe('0 secs');
      expect(this.formatDuration(10)).toBe('0.01 secs');
      expect(this.formatDuration(999)).toBe('0.999 secs');
      expect(this.formatDuration(secs)).toBe('1 secs');
      expect(this.formatDuration(10 * secs)).toBe('10 secs');
      expect(this.formatDuration(59 * secs)).toBe('59 secs');
      expect(this.formatDuration(60 * secs)).toBe('1 mins');
      expect(this.formatDuration(61 * secs)).toBe('1 mins 1 secs');
      expect(this.formatDuration(59 * mins)).toBe('59 mins');
      expect(this.formatDuration(60 * mins)).toBe('1 hours');
      expect(this.formatDuration(3 * hours + 28 * mins + 53 * secs + 127)).toBe('3 hours 28 mins 53 secs');
      return expect(this.formatDuration(3 * hours + 53 * secs + 127)).toBe('3 hours 53 secs');
    });
  });

}).call(this);

//# sourceMappingURL=duration-format.spec.js.map
