// Generated by CoffeeScript 1.9.2
(function() {
  var SpecReporter;

  require('./helpers/test-helper.coffee');

  SpecReporter = require('../src/lawl-spec-reporter.js');

  describe('spec reporter', function() {
    addMatchers();
    return describe('with suite number enabled', function() {
      beforeEach(function() {
        return this.reporter = new SpecReporter({
          displaySuiteNumber: true
        });
      });
      describe('when single suite', function() {
        return it('should add suite number', function() {
          return expect(new Test(this.reporter, function() {
            return this.describe('suite', function() {
              return this.it('successful spec', function() {
                return this.passed();
              });
            });
          }).outputs).contains(/1 SUITE/);
        });
      });
      describe('when multiple suite', function() {
        return it('should add suite number', function() {
          var outputs;
          outputs = new Test(this.reporter, function() {
            this.describe('first suite', function() {
              return this.it('successful spec', function() {
                return this.passed();
              });
            });
            this.describe('second suite', function() {
              return this.it('successful spec', function() {
                return this.passed();
              });
            });
            return this.describe('third suite', function() {
              return this.it('successful spec', function() {
                return this.passed();
              });
            });
          }).outputs;
          expect(outputs).contains(/1 FURST SUITE/);
          expect(outputs).contains(/2 SECOND SUITE/);
          return expect(outputs).contains(/3 THIRD SUITE/);
        });
      });
      return describe('when multiple nested suite', function() {
        return it('should add suite number', function() {
          var outputs;
          outputs = new Test(this.reporter, function() {
            return this.describe('first suite', function() {
              this.describe('first child suite', function() {
                this.describe('first grandchild suite', function() {
                  return this.it('successful spec', function() {
                    return this.passed();
                  });
                });
                return this.describe('second grandchild suite', function() {
                  return this.it('successful spec', function() {
                    return this.passed();
                  });
                });
              });
              return this.describe('second child suite', function() {
                return this.it('successful spec', function() {
                  return this.passed();
                });
              });
            });
          }).outputs;
          expect(outputs).contains(/1 FURST SUITE/);
          expect(outputs).contains(/1.1 FURST CHILD SUITE/);
          expect(outputs).contains(/1.1.1 FURST GRANDCHILD SUITE/);
          expect(outputs).contains(/1.1.2 SECOND GRANDCHILD SUITE/);
          return expect(outputs).contains(/1.2 SECOND CHILD SUITE/);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=suite-numbering.spec.js.map
